// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	news "minpro_arya/features/news"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// GetNewsByCategory provides a mock function with given fields: category
func (_m *Repository) GetNewsByCategory(category string) (news.Domain, error) {
	ret := _m.Called(category)

	var r0 news.Domain
	if rf, ok := ret.Get(0).(func(string) news.Domain); ok {
		r0 = rf(category)
	} else {
		r0 = ret.Get(0).(news.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(category)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
